# this is the source directory where the files you want to move from
srcDirs: 
  - /home/shoaib/forjf/file_exchange
  - /home/shoaib/tmp
# this is the root directory where you have subdirs to which you want
# to move files to, ex: /home/shoaib42/forjf/movies /home/shoaib42/forjf/docs
destRootDir: /home/shoaib/forjf
# a list of subdirs you want to exclude from being listed
excludeDirs:
  - lost+found
  - file_exchange
  - uncat
# a list of cidrs, from where the client can connect
allowedCIDRs:
  - 127.0.0.1/32
  - 192.168.0.0/24
serverBindAddr: 127.0.0.1
serverBindPort: 8089
# the usrId and grpId to chown to, happens after the move.
chownUsrGrp: 1000:1000
